version: '3.2'

services:
  corteza:
    image: cortezaproject/corteza:${CORTEZA_VERSION}
    environment:
      DOMAIN: corteza

  cypress:
    image: cypress/included:${CYPRESS_VERSION}
    depends_on: [ corteza ]
    entrypoint: cypress run
    ipc: host # does not work in docker without it
    working_dir: /e2e
    volumes:
      - ./:/e2e
