version: '3.2'

services:
  corteza:
    image: cortezaproject/corteza:${CORTEZA_VERSION}
    environment:
      DOMAIN: corteza

  cypress:
    image: cypress/included:${CYPRESS_VERSION}
    depends_on: [ corteza ]
    ipc: host # does not work in docker without it
    working_dir: /e2e
    volumes:
      - ./:/e2e

  mailhog:
   image: mailhog/mailhog:latest
   ports:
     - 8025:8025
     - 1025:1025
