== Add environmental variables

=== Set basic host settings

The generic host and user settings are in the `cypress.env.json` file.

[NOTE]
====
The main configuration file is the `cypress.env.json`, but do try to separate the host settings and main configuration settings for cypress.
====

[source,json]
----
{
  "HOST": "http://localhost:3000",
  "BASE_URL": "http://localhost:3000",
  "ADMIN_URL": "http://localhost:8080",
  "COMPOSE_URL": "http://localhost:8081",
  "WORKFLOW_URL": "http://localhost:8082",
  "REPORTER_URL": "http://localhost:8083",
  "ONE_URL": "http://localhost:8084",
  "PRIVACY_URL": "http://localhost:8085",
  "USER_EMAIL": "cypress@test.com",
  "USER_PASSWORD": "cypress123",
  "USER_PASSWORD_NEW": "newcypress123",
  "USER_EMAIL_NEW": "permissions@email.com",
  "USER_DPO": "dpo@email.com",
  "USER_DPO_USER_PASSWORD": "dpo@email.com",
}
----

== Running the tests

[source,bash]
----
$ yarn cypress open
----

or

[source,bash]
----
$ yarn run cy:open
----

== Running specific cypress tests using CLI

[source,bash]
----
$ yarn cypress run --spec <path-to-spec-file>
----

.Example:
[source,bash]
----
$ cypress run --spec cypress/e2e/basic-functionalities/local-tests/server/Create_user.cy.js
----

== SMTP support

The SMTP testing is done via https://github.com/mailhog/MailHog[mailhog].

.Running the mailhog in background
[source,bash]
----
$ docker-compose up -d mailhog
----

[NOTE]
====
The mailhog container is ephemeral, so all the emails will NOT be persisted in the container (you will lose emails when the mailhog is stopped).
====

You can preview all the emails manually by visiting `http://localhost:8025`

.SMTP server settings
[Attributes]
|===
|Setting |Value

|**Server**|localhost
|**Port**|1025
|**User**|<empty>
|**Password**|<empty>
|===


== Running the tests dockerized

=== Set versions

Create an `.env` file and specify the Corteza and Cypress versions.
The host configuration should be specified either via `cypress.env.json` or by environment variables in the `docker-compose.yaml` configuration.

[NOTE]
====
Refer to the `.env.example` file for an idea.
====

=== Pull Images

[source,bash]
----
$ docker-compose pull
----

=== Run headless

[source,bash]
----
$ docker-compose run --entrypoint='cypress run --spec cypress/e2e/basic-functionalities/local-tests/server/index.cy.js cypress' cypress
----

=== Run Cypress with screen

[source,bash]
----
$ docker-compose -f docker-compose.yaml -f docker-compose.screen.yaml up --exit-code-from cypress
----

== Custom commands

This project also adds several custom commands in cypress/support/commands.js. They are useful to create one or more default todos from the tests.

[source,bash]
----
Cypress.Commands.add('login', (params) => {
  // custom login function
})
----

== Troubleshooting

=== Use in case of a CSRF token issue

[source,json]
----
{ "AUTH_CSRF_ENABLED": false }
----