import './admin/enable/index.cy'
import './mfa/index.cy'
import './Profile_tab.cy'
import './Corteza_logo.cy'
import './Authorized_clients.cy'
import './links/index.cy'
import './Enable_password_reset.cy'
import './Password_reset.cy'
